[package]
name = "n5011"
version = "0.1.0"
authors = ["Artem Khomenko <_mag12@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
futures = "0.3.5"
tokio = { version =  "1.3.0", features = ["rt-threaded", "macros", "time"] }
pretty_env_logger = "0.4.0"
teloxide = "0.3.1"

# Used to setup a webhook
warp = "0.3.0"
reqwest = "0.11.2"
serde_json = "1.0.57"

# My
arraylib = "0.3.0"
rand = "0.8.3"

# Database
once_cell = "1.4.0"
tokio-postgres = { version = "0.7.0", features = ["with-chrono-0_4"] }
#openssl = "0.10.32"
#tokio-openssl = "0.6.1"

postgres-native-tls = ""
native-tls = ""