[package]
name = "n5011"
version = "0.1.0"
authors = ["Artem Khomenko <_mag12@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
futures = "0.3.5"
tokio = { version =  "0.3.7", features = ["macros", "time"] }
# tokio = { version = "0.3.7", features = ["full"] }
pretty_env_logger = "0.4.0"
teloxide = "0.3.4"

# Used to setup a webhook
warp = "0.2.2"
reqwest = "0.10.4"
serde_json = "1.0.50"

# Database
once_cell = "1.4.0"
# tokio-postgres = { version = "0.7.0", features = ["with-chrono-0_4"] }
tokio-postgres = "0.7.0"
#openssl = "0.10.32"
#tokio-openssl = "0.6.1"

postgres-native-tls = "0.5.0"
native-tls = "0.2.7"